import React, { useEffect, useState } from 'react'
import Card from '../components/Card'
import FormField from '../components/FormField'
import Loader from '../components/Loader'
import { toast } from 'react-hot-toast'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post, index) => (
        <div key={post._id} className={`animate-fade-in-up`} style={{ animationDelay: `${index * 100}ms` }}>
          <Card {...post} />
        </div>
      ))
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);
  const BASE_URL = process.env.REACT_APP_BASE_URL
  const POST_DATA_API = BASE_URL + "/post"

  const fetchPosts = async () => {
    setLoading(true)

    try {

      //The fetch function in JavaScript returns a Promise that resolves to the Response object representing the response to the request. 
      const response = await fetch(POST_DATA_API, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      })
      console.log("response is", response)
      if (response.ok) {
        const result = await response.json();
        console.log("result is", result)
        setAllPosts(result.data.reverse());
      }

    } catch (error) {
      toast.error("Error while getting posts")
    }
    finally {
      setLoading(false)
    }
  }

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) =>
          item.name.toLowerCase().includes(searchText.toLowerCase()) ||
          item.prompt.toLowerCase().includes(searchText.toLowerCase()) ||
          item.model.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult);
      }, 500),
    );
  };

  useEffect(() => {
    fetchPosts()
  }, [])

  return (
    <section className="max-w-7xl mx-auto mt-4 mb-20">
      <div className="text-center mb-16 animate-fade-in-up">
        <h1 className="heading-hero text-[40px] sm:text-[60px] leading-[0.9] mb-6">
          The <span className="text-gradient-minimal">Community</span> Showcase
        </h1>
        <p className="text-zinc-400 text-[18px] max-w-[600px] mx-auto delay-100 leading-relaxed font-light">
          Browse through a curated collection of imaginative and visually stunning images generated by AI models.
        </p>
      </div>

      <div className="max-w-xl mx-auto mb-16 animate-fade-in-up delay-200">
        <FormField
          labelName="Search"
          type="text"
          name="text"
          placeholder="Search by name or prompt..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-400 text-xl mb-3">
                Showing Results for <span className="text-white font-bold">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-4">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home